### PR TITLE
Msvc16

### PR DESCRIPTION
**Pull request by eisenhauer**

### CODE REVIEW

**Comment by chuckatkins** [comment]
I think this will work with the original commented out settings but also passing the extra ctest arguments in the build:
```diff
diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
index 1d204fd..9d5893c 100644
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -113,8 +113,8 @@ jobs:
         include:
         - jobname: windows-msvc
           vm: windows-latest
-       #   os: Windows
-       #   ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64
+          os: Windows
+          ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64
        # - jobname: windows-clang
        #   vm: windows-latest
        #   os: Windows
@@ -137,7 +137,7 @@ jobs:
       run: scripts/ci/gh-actions/run.sh configure ${{ matrix.ctest_args }}
       shell: bash
     - name: Build
-      run: scripts/ci/gh-actions/run.sh build
+      run: scripts/ci/gh-actions/run.sh build ${{ matrix.ctest_args }}
       shell: bash
     - name: Test
       run: scripts/ci/gh-actions/run.sh test
```

**Comment by eisenhauer** [comment]
I think that was the first thing I tried, but let me give it a shot again…

From: Chuck Atkins ***@***.***>
Date: Monday, April 5, 2021 at 1:41 PM
To: GTkorvo/atl ***@***.***>
Cc: Eisenhauer, Greg S ***@***.***>, Author ***@***.***>
Subject: Re: [GTkorvo/atl] Msvc16 (#18)

I think this will work with the original commented out settings but also passing the extra ctest arguments in the build:

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml

index 1d204fd..9d5893c 100644

--- a/.github/workflows/build-and-test.yml

+++ b/.github/workflows/build-and-test.yml

@@ -113,8 +113,8 @@ jobs:

         include:

         - jobname: windows-msvc

           vm: windows-latest

-       #   os: Windows

-       #   ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64

+          os: Windows

+          ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64

        # - jobname: windows-clang

        #   vm: windows-latest

        #   os: Windows

@@ -137,7 +137,7 @@ jobs:

       run: scripts/ci/gh-actions/run.sh configure ${{ matrix.ctest_args }}

       shell: bash

     - name: Build

-      run: scripts/ci/gh-actions/run.sh build

+      run: scripts/ci/gh-actions/run.sh build ${{ matrix.ctest_args }}

       shell: bash

     - name: Test

       run: scripts/ci/gh-actions/run.sh test

**Comment by eisenhauer** [comment]
Ah, I think I had it without the change to the build action.

Thanks!
g

From: Chuck Atkins ***@***.***>
Date: Monday, April 5, 2021 at 1:41 PM
To: GTkorvo/atl ***@***.***>
Cc: Eisenhauer, Greg S ***@***.***>, Author ***@***.***>
Subject: Re: [GTkorvo/atl] Msvc16 (#18)

I think this will work with the original commented out settings but also passing the extra ctest arguments in the build:

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml

index 1d204fd..9d5893c 100644

--- a/.github/workflows/build-and-test.yml

+++ b/.github/workflows/build-and-test.yml

@@ -113,8 +113,8 @@ jobs:

         include:

         - jobname: windows-msvc

           vm: windows-latest

-       #   os: Windows

-       #   ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64

+          os: Windows

+          ctest_args: -DCTEST_CMAKE_GENERATOR="Visual Studio 16" -DCTEST_CMAKE_GENERATOR_PLATFORM=x64

        # - jobname: windows-clang

        #   vm: windows-latest

        #   os: Windows

@@ -137,7 +137,7 @@ jobs:

       run: scripts/ci/gh-actions/run.sh configure ${{ matrix.ctest_args }}

       shell: bash

     - name: Build

-      run: scripts/ci/gh-actions/run.sh build

+      run: scripts/ci/gh-actions/run.sh build ${{ matrix.ctest_args }}

       shell: bash

     - name: Test

       run: scripts/ci/gh-actions/run.sh test

**Comment by chuckatkins** [comment]
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4f1d119..28474b2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,6 +39,15 @@ if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
   set_property(CACHE CMAKE_BUILD_TYPE PROPERTY VALUE RelWithDebInfo)
 endif()
 
+
+# Silence MSVC warnings
+if(MSVC)
+  add_definitions(
+    -D_CRT_SECURE_NO_DEPRECATE
+    -D_CRT_SECURE_NO_WARNINGS
+    -D_SCL_SECURE_NO_DEPRECATE)
+endif()
+
 include(CMakeDependentOption)
 
 # Setup shared library defaults.  If explicitly specified somehow, then default
```

**Pull request merged**
