### PR TITLE
CI: Add initial CI support Linux via GitHub Actions

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@eisenhauer this is stemming from trying to bring PGI back in the adios2 CI and spending some quality time squashing warnings in the various components of sst.

**Comment by eisenhauer** [comment]
All reasonable...

**Comment by chuckatkins** [comment]
Unfortunately the nature of how the GitHub Actions works, none of it will run until there's something in master at least.  So expect a followup immediately that will be working through any issues that may be present in this one.

**Comment by eisenhauer** [comment]
I figured that was the next step!

**Comment by eisenhauer** [comment]
Let me know if I can help with any of it.

**Pull request merged**
